//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSE.Assignment21.MVCClient.JobServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/FSE.Assignment21.Task02")]
    [System.SerializableAttribute()]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExperienceField, value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Job Description")]
        public string JobDescription {
            get {
                return this.JobDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.JobDescriptionField, value) != true)) {
                    this.JobDescriptionField = value;
                    this.RaisePropertyChanged("JobDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Job Id")]
        public int JobId {
            get {
                return this.JobIdField;
            }
            set {
                if ((this.JobIdField.Equals(value) != true)) {
                    this.JobIdField = value;
                    this.RaisePropertyChanged("JobId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Job Role")]
        public string JobRole {
            get {
                return this.JobRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobRoleField, value) != true)) {
                    this.JobRoleField = value;
                    this.RaisePropertyChanged("JobRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobServiceReference.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobs", ReplyAction="http://tempuri.org/IJobService/OpeningJobsResponse")]
        FSE.Assignment21.MVCClient.JobServiceReference.Job[] OpeningJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobs", ReplyAction="http://tempuri.org/IJobService/OpeningJobsResponse")]
        System.Threading.Tasks.Task<FSE.Assignment21.MVCClient.JobServiceReference.Job[]> OpeningJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobsByRole", ReplyAction="http://tempuri.org/IJobService/OpeningJobsByRoleResponse")]
        FSE.Assignment21.MVCClient.JobServiceReference.Job[] OpeningJobsByRole(string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobService/OpeningJobsByRole", ReplyAction="http://tempuri.org/IJobService/OpeningJobsByRoleResponse")]
        System.Threading.Tasks.Task<FSE.Assignment21.MVCClient.JobServiceReference.Job[]> OpeningJobsByRoleAsync(string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobServiceChannel : FSE.Assignment21.MVCClient.JobServiceReference.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<FSE.Assignment21.MVCClient.JobServiceReference.IJobService>, FSE.Assignment21.MVCClient.JobServiceReference.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FSE.Assignment21.MVCClient.JobServiceReference.Job[] OpeningJobs() {
            return base.Channel.OpeningJobs();
        }
        
        public System.Threading.Tasks.Task<FSE.Assignment21.MVCClient.JobServiceReference.Job[]> OpeningJobsAsync() {
            return base.Channel.OpeningJobsAsync();
        }
        
        public FSE.Assignment21.MVCClient.JobServiceReference.Job[] OpeningJobsByRole(string role) {
            return base.Channel.OpeningJobsByRole(role);
        }
        
        public System.Threading.Tasks.Task<FSE.Assignment21.MVCClient.JobServiceReference.Job[]> OpeningJobsByRoleAsync(string role) {
            return base.Channel.OpeningJobsByRoleAsync(role);
        }
    }
}
