//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSE.Assignment21.MVCClient.SelfHostedServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelfHostedServiceReference.ISelfHostingService")]
    public interface ISelfHostingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfHostingService/SayHello", ReplyAction="http://tempuri.org/ISelfHostingService/SayHelloResponse")]
        string SayHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfHostingService/SayHello", ReplyAction="http://tempuri.org/ISelfHostingService/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfHostingService/TodayProgram", ReplyAction="http://tempuri.org/ISelfHostingService/TodayProgramResponse")]
        string TodayProgram(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISelfHostingService/TodayProgram", ReplyAction="http://tempuri.org/ISelfHostingService/TodayProgramResponse")]
        System.Threading.Tasks.Task<string> TodayProgramAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISelfHostingServiceChannel : FSE.Assignment21.MVCClient.SelfHostedServiceReference.ISelfHostingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelfHostingServiceClient : System.ServiceModel.ClientBase<FSE.Assignment21.MVCClient.SelfHostedServiceReference.ISelfHostingService>, FSE.Assignment21.MVCClient.SelfHostedServiceReference.ISelfHostingService {
        
        public SelfHostingServiceClient() {
        }
        
        public SelfHostingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelfHostingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelfHostingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelfHostingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string name) {
            return base.Channel.SayHello(name);
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync(string name) {
            return base.Channel.SayHelloAsync(name);
        }
        
        public string TodayProgram(string name) {
            return base.Channel.TodayProgram(name);
        }
        
        public System.Threading.Tasks.Task<string> TodayProgramAsync(string name) {
            return base.Channel.TodayProgramAsync(name);
        }
    }
}
